### ISSUE TITLE
能否支持输出sushi调轴时的日志

### ISSUE THREAD

**Issue by kysdm** [arition/SubRenamer#1]
sushi输出的日志，大致可以看出字幕平移时轴是否正确
希望可以加入

**Comment by arition** [comment]
我试了一下，感觉比较困难。

sushi在windows上使用了```colorama```来实现控制台彩色输出。```colorama```直接接管了```stdout```，导致主程序没办法捕获输出。

sushi也没有提供直接输出log的选项。

**Comment by tonyhsie** [comment]
> 我试了一下，感觉比较困难。
> 
> sushi在windows上使用了`colorama`来实现控制台彩色输出。`colorama`直接接管了`stdout`，导致主程序没办法捕获输出。
> 
> sushi也没有提供直接输出log的选项。

C# 是可以即時獲取 Sushi 輸出的
它是輸出到 StandardError，你只要 RedirectStandardError 設起來，就能用 StreamReader 去 Read 了
