### ISSUE TITLE
提供两点改进意见，使应用程序更加完美

### ISSUE THREAD

**Issue by Karanoyo** [arition/SubRenamer#102]
## 1. 命令行(右键菜单)的支持

目前使用命令行调用 SubRenamer 无法接收字幕/视频文件：
(字幕重命名程序好像都不支持命令行)

```
SubRenamer.exe "1.ass" "1.mkv" "2.ass" "2.mkv"
```
![Snipaste_2024-01-05_03-25-09](https://github.com/arition/SubRenamer/assets/93567765/c738f393-9520-4e53-95e8-77911dc3e3ff)

## 2. 将列调整为合适的大小

目前 SubRenamer 无法记忆窗口的最大化状态，导致无法目视检查文件名较长的字幕后缀

```
建议：在窗口最大化状态时，添加字幕和视频后，自动将「最终文件名」预览列调整为合适的大小
(可以的话，希望窗口可以记忆最大化状态，下次打开还是最大化的窗口)
```
![Snipaste_2024-01-05_03-25-25](https://github.com/arition/SubRenamer/assets/93567765/45d08f24-e994-4be9-956d-c5040478652b)
![Snipaste_2024-01-05_03-25-38](https://github.com/arition/SubRenamer/assets/93567765/9e6be5c8-11d8-48ca-8142-270a0d3782e8)

------

*祈祷大佬采纳上述意见*

**Comment by arition** [comment]
Implemented in https://github.com/arition/SubRenamer/commit/a29595c9fa53eb6466a03fc0fc06bf2cff894270

**Comment by Karanoyo** [comment]
> Implemented in [a29595c](https://github.com/arition/SubRenamer/commit/a29595c9fa53eb6466a03fc0fc06bf2cff894270)

感谢大佬成全。(●'◡'●)
