### ISSUE TITLE
能否自行添加文件文件后缀呢？

### ISSUE THREAD

**Issue by CXido** [arition/SubRenamer#23]
就是有一些番的字幕它是没有后缀的，要是使用这个工具就会自动换成视频的名字，能否做成像其他字幕软件一样可以自己自定义后缀？
![2](https://user-images.githubusercontent.com/55381745/149646833-5a351729-0ca5-45bf-bb4f-566f24bf87b9.png)

**Comment by arition** [comment]
Implemented in fd463e47860841e256edc3d818045dbbb9e1515b.
