### ISSUE TITLE
如果之前命名过一次，再加新字幕的话就不会重命名新的字幕

### ISSUE THREAD

**Issue by CXido** [arition/SubRenamer#29]
如图
![1](https://user-images.githubusercontent.com/55381745/151540164-1a5ebb12-5b10-4119-917c-4d6dcf4572ec.jpg)

**Comment by arition** [comment]
无法重现，能详细描述一下步骤嘛

**Comment by CXido** [comment]
首先先把tc后缀的文件命名好，之后再加入sc后缀未命名的文件，同时把sc和tc一起拖进去命名
结果就是只能识别到tc，sc后缀没有一起放进去命名（可是tc已经有是视频的名字了）

**Comment by arition** [comment]
我懂你意思了，这个情景下出现的问题不太可能修复。字幕名字相差太大了，肯定不能当作一集的简中/繁中字幕。如果要修的话就可能会引入把不同集数的字幕当作同一集字幕的bug。
