### ISSUE TITLE
feature：目前使用后感觉缺少几个功能，望日后能添加吧

### ISSUE THREAD

**Issue by senjyouhara** [arition/SubRenamer#38]
### 使用了下软件  目前感觉软件还缺少几个功能  如果合适的话希望能添加进去

* 添加进去的列表无法单条删除，只能清空列表
* 添加进去的列表不支持通过手动拖拽调整顺序
* 不支持重命名操作，目前是只能根据原有视频名称来重命名字幕，无法使用新的命名方式对视频和字幕来进行命名操作

**Comment by arition** [comment]
1和2可以考虑加入，3的话应该不会考虑加入。如果需要用3这样的功能的话，可以考虑其他的通用改名工具。

**Comment by senjyouhara** [comment]
好的
