### ISSUE TITLE
对于有序列号对应的歌词文件可以支持重命名吗？

### ISSUE THREAD

**Issue by LemonSoda-RPG** [arition/SubRenamer#63]
对于有序列号对应的歌词文件可以支持重命名吗？像图片这种
![image](https://user-images.githubusercontent.com/85331400/205224408-31e9023f-2f97-4e4c-ad7c-e5026a113875.png)

**Comment by LemonSoda-RPG** [comment]
能否通过拓展文件后缀支持此功能？

**Comment by arition** [comment]
这些不属于视频和字幕，所以不打算做默认支持。但是你可以用选择视频和选择字幕按钮来强行加入文件

![image](https://user-images.githubusercontent.com/3581094/206998077-2f0cc052-ab72-4688-ae36-a8ca9a71c217.png)
