### ISSUE TITLE
希望能增加 Dark Mode

### ISSUE THREAD

**Issue by snoopyzx963** [arition/SubRenamer#68]
希望能增加 Dark Mode

目前使用下來非常好用，感謝作者!

**Comment by arition** [comment]
https://github.com/arition/SubRenamer/commit/06939431b2213362b20250662bfdfb3d0fa21870

https://github.com/arition/SubRenamer/releases/tag/v3.2.0

**Comment by snoopyzx963** [comment]
**Appreciate!**
